### PR TITLE
Support telemetry 1.0

### PR DESCRIPTION
**Pull request by thiagogsr**

### CODE REVIEW

**Review by hauleth — APPROVED** [review]

**Comment by wiserfirst** [comment]
@hauleth the build is failing on CircleCI because `$CHECKOUT_KEY` variable is no longer valid. It would be great if you could update it in CircleCI and retry the build. Thanks 🙏

**Comment by maysgar** [comment]
Do we have any updates on this?

**Comment by wiserfirst** [comment]
I reckon it would be really helpful for many people who use this library if this PR can be merged and a new version can be published. Thanks! cc @tsloughter @hauleth @deadtrickster 🙏

**Comment by tsloughter** [comment]
Oh, for some reason I thought I didn't own the hex package, but I just checked and I do :).

So I can publish a new version, but all the CI is failing. Is anyone able to update that? Move to github actions. Or should I just merge and publish? Obviously because this has been deprecated in favor of OpenTelemetry we are only handling bugs and small improvements like this.

**Comment by tsloughter** [comment]
Not publishing yet because I get 3 test failures. They are surely unrelated to the fact its using telemetry 1.0 but I don't want to just publish in case there is an actual issue we should fix:

```

  1) test verify attributes (OpencensusTest)
     test/opencensus_test.exs:9
     Assertion with == failed
     code:  assert Logger.metadata() |> Keyword.keys() |> Enum.sort() == [:span_id, :trace_id, :trace_options]
     left:  [:span_ctx, :span_id, :trace_id, :trace_options]
     right: [:span_id, :trace_id, :trace_options]
     stacktrace:
       test/opencensus_test.exs:21: (test)

..

  2) test set_logger_metadata/0 can set and unset trace metadata (Opencensus.LoggerTest)
     test/opencensus_logger_test.exs:52
     setup: ocp.with_child_span set Logger metadata!
     code: assert Logger.metadata() == [], "setup: ocp.with_child_span set Logger metadata!"
     stacktrace:
       test/opencensus_logger_test.exs:57: (test)

.

  3) test set_logger_metadata/1 can set trace metadata (Opencensus.LoggerTest)
     test/opencensus_logger_test.exs:5
     setup: ocp.with_child_span set Logger metadata!
     code: assert Logger.metadata() == [], "setup: ocp.with_child_span set Logger metadata!"
     stacktrace:
       test/opencensus_logger_test.exs:16: (test)

..

Finished in 0.2 seconds (0.00s async, 0.2s sync)
8 tests, 3 failures
```

**Pull request merged**
